server:
  port: 1215
spring:
  application:
    name: CloudGateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: pro
        group: my-group
    sentinel:
      transport:
        dashboard: localhost:1212
        port: 8710
    gateway:
      routes:
        - id: CloudGoods
          uri: lb://CloudGoods/
          predicates:
            - Path=/goods/**
            - After=2022-08-12T16:19:48.947+08:00[Asia/Shanghai]
#            - MyHeader=name,OYear
          filters:
            - CalServiceTime=a,b
        - id: baidu
          uri: https://www.baidu.com
          predicates:
            - Path=/**